# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Set ZSH variables before loading oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="powerlevel10k/powerlevel10k"

# Disable gitstatus as it seems annoying
# https://github.com/romkatv/powerlevel10k/issues/246
POWERLEVEL9K_DISABLE_GITSTATUS=true

# Configuration
# --------------------------------------

source $HOME/.zsh/config/variables.zsh
source $HOME/.zsh/config/aliases.zsh

plugins=(
  git
  fzf-tab
  zsh-autosuggestions
  fast-syntax-highlighting
  zsh-completions
)

ZSH_AUTOSUGGEST_STRATEGY=(history completion)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Graphite CLI completion
if command -v gt &>/dev/null; then
  eval "$(gt completion)"
fi
