# Configuration
# --------------------------------------

source $HOME/.zsh/config/variables.zsh
source $HOME/.zsh/config/aliases.zsh

plugins=(
  git
  zsh-autosuggestions
)

ZSH_AUTOSUGGEST_STRATEGY=(history completion)

source $ZSH/oh-my-zsh.sh
